export const topics = [
  {
    name: 'Mothúcháin — Emotions',
    wordsAndImages: [
      { en: 'happy', fi: 'sásta', img: 'emotions/happy.png' },
      { en: 'excited', fi: 'spleodrach', img: 'emotions/excited.png' },
      { en: 'proud', fi: 'bródúil', img: 'emotions/proud.png' },
      { en: 'in love', fi: 'i ngrá', img: 'emotions/inlove.png' },
      { en: 'grateful', fi: 'buíoch', img: 'emotions/grateful.png' },
      { en: 'confident', fi: 'muiníneach', img: 'emotions/confident.png' },
      { en: 'sad', fi: 'brónach', img: 'emotions/sad.png' },
      { en: 'angry', fi: 'feargach', img: 'emotions/angry.png' },
      { en: 'scared', fi: 'scanraithe', img: 'emotions/scared.png' },
      { en: 'embarrassed', fi: 'náirithe', img: 'emotions/embarrassed.png' },
      { en: 'frustrated', fi: 'frustrachas', img: 'emotions/frustrated.png' },
      { en: 'surprised', fi: 'ionadh', img: 'emotions/surprised.png' }
    ]
  },
  {
    name: 'Ainmhithe — Animals',
    wordsAndImages: [
      { en: 'bear', fi: 'béar', img: 'animals/bear.png' },
      { en: 'bee', fi: 'beach', img: 'animals/bee.png' },
      { en: 'bird', fi: 'éan', img: 'animals/bird.png' },
      { en: 'butterfly', fi: 'féileacán', img: 'animals/butterfly.png' },
      { en: 'cat', fi: 'cat', img: 'animals/cat.png' },
      { en: 'chicken', fi: 'sicín', img: 'animals/chicken.png' },
      { en: 'cow', fi: 'bó', img: 'animals/cow.png' },
      { en: 'dog', fi: 'madra', img: 'animals/dog.png' },
      { en: 'elephant', fi: 'eilifint', img: 'animals/elephant.png' },
      { en: 'fish', fi: 'iasc', img: 'animals/fish.png' },
      { en: 'fly', fi: 'cuileog', img: 'animals/fly.png' },
      { en: 'horse', fi: 'capall', img: 'animals/horse.png' },
      { en: 'lion', fi: 'leon', img: 'animals/lion.png' },
      { en: 'mosquito', fi: 'meachán', img: 'animals/mosquito.png' },
      { en: 'mouse', fi: 'luch', img: 'animals/mouse.png' },
      { en: 'pig', fi: 'muc', img: 'animals/pig.png' },
      { en: 'rabbit', fi: 'coinín', img: 'animals/rabbit.png' },
      { en: 'rat', fi: 'francach', img: 'animals/rat.png' },
      { en: 'seagull', fi: 'faoileán', img: 'animals/seagull.png' },
      { en: 'sheep', fi: 'caora', img: 'animals/sheep.png' }
    ]
  },
    {
    name: 'Bia — Food',
    wordsAndImages: [
      { en: 'bread', fi: 'arán', img: 'food/bread.png' },
      { en: 'butter', fi: 'im', img: 'food/butter.png' },
      { en: 'carrot', fi: 'cairéad', img: 'food/carrot.png' },
      { en: 'cheese', fi: 'cáis', img: 'food/cheese.png' },
      { en: 'cucumber', fi: 'cúcamar', img: 'food/cucumber.png' },
      { en: 'egg', fi: 'ubh', img: 'food/egg.png' },
      { en: 'garlic', fi: 'gairleog', img: 'food/garlic.png' },
      { en: 'milk', fi: 'bainne', img: 'food/milk.png' },
      { en: 'onion', fi: 'oinniún', img: 'food/onion.png' },
      { en: 'pasta', fi: 'pasta', img: 'food/pasta.png' },
      { en: 'potato', fi: 'práta', img: 'food/potato.png' },
      { en: 'rice', fi: 'rís', img: 'food/rice.png' },
      { en: 'salad', fi: 'sailéad', img: 'food/salad.png' },
      { en: 'soup', fi: 'anraith', img: 'food/soup.png' },
      { en: 'yoghurt', fi: 'iogart', img: 'food/yoghurt.png' }
    ]
  },
  {
    name: 'Torthaí — Fruits',
    wordsAndImages: [
      { en: 'apple', fi: 'úll', img: 'fruits/apple.png' },
      { en: 'banana', fi: 'banán', img: 'fruits/banana.png' },
      { en: 'blueberry', fi: 'fraochán gorm', img: 'fruits/blueberry.png' },
      { en: 'cherry', fi: 'silín', img: 'fruits/cherry.png' },
      { en: 'grapefruit', fi: 'seadóg', img: 'fruits/grapefruit.png' },
      { en: 'grapes', fi: 'fíonchaora', img: 'fruits/grapes.png' },
      { en: 'kiwi', fi: 'cíobhaí', img: 'fruits/kiwi.png' },
      { en: 'lemon', fi: 'líomóid', img: 'fruits/lemon.png' },
      { en: 'lime', fi: 'liómón glas', img: 'fruits/lime.png' },
      { en: 'mango', fi: 'mangó', img: 'fruits/mango.png' },
      { en: 'orange', fi: 'oráiste', img: 'fruits/orange.png' },
      { en: 'peach', fi: 'péitseog', img: 'fruits/peach.png' },
      { en: 'pear', fi: 'piorra', img: 'fruits/pear.png' },
      { en: 'pineapple', fi: 'ainniúin', img: 'fruits/pineapple.png' },
      { en: 'plum', fi: 'prún', img: 'fruits/plum.png' },
      { en: 'raspberry', fi: 'sú craobh', img: 'fruits/raspberry.png' },
      { en: 'strawberry', fi: 'sú talún', img: 'fruits/strawberry.png' },
      { en: 'watermelon', fi: 'mealbh uisce', img: 'fruits/watermelon.png' }
    ]
  },

    {
    name: 'Feithiclí — Vehicles',
    wordsAndImages: [
      { en: 'airplane', fi: 'eitleán', img: 'vehicles/airplane.png' },
      { en: 'ambulance', fi: 'otharcharr', img: 'vehicles/ambulance.png' },
      { en: 'bicycle', fi: 'rothar', img: 'vehicles/bicycle.png' },
      { en: 'boat', fi: 'bád', img: 'vehicles/boat.png' },
      { en: 'bus', fi: 'bus', img: 'vehicles/bus.png' },
      { en: 'car', fi: 'carr', img: 'vehicles/car.png' },
      { en: 'drone', fi: 'dron', img: 'vehicles/drone.png' },
      { en: 'fire truck', fi: 'tarrtháil tine', img: 'vehicles/fire_truck.png' },
      { en: 'helicopter', fi: 'héileacaptar', img: 'vehicles/helicopter.png' },
      { en: 'hot air balloon', fi: 'balún aeir the', img: 'vehicles/hot_air_balloon.png' },
      { en: 'metro', fi: 'meitreo', img: 'vehicles/metro.png' },
      { en: 'motorcycle', fi: 'gluaisrothar', img: 'vehicles/motorcycle.png' },
      { en: 'police car', fi: 'carr póilíní', img: 'vehicles/police_car.png' },
      { en: 'taxi', fi: 'tacsaí', img: 'vehicles/taxi.png' },
      { en: 'tractor', fi: 'trucail', img: 'vehicles/tractor.png' },
      { en: 'train', fi: 'traein', img: 'vehicles/train.png' },
      { en: 'tram', fi: 'tram', img: 'vehicles/tram.png' },
      { en: 'truck', fi: 'leoraí', img: 'vehicles/truck.png' },
      { en: 'van', fi: 'veain', img: 'vehicles/van.png' }
    ]
  },
  {
    name: 'Baile — Home',
    wordsAndImages: [
      { en: 'bathroom', fi: 'seomra folctha', img: 'home/bathroom.png' },
      { en: 'bed', fi: 'leaba', img: 'home/bed.png' },
      { en: 'bedroom', fi: 'seomra codlata', img: 'home/bedroom.png' },
      { en: 'blanket', fi: 'brat', img: 'home/blanket.png' },
      { en: 'carpet', fi: 'raig', img: 'home/carpet.png' },
      { en: 'ceiling', fi: 'uasteach', img: 'home/ceiling.png' },
      { en: 'chair', fi: 'cathaoir', img: 'home/chair.png' },
      { en: 'cupboard', fi: 'cófra', img: 'home/cupboard.png' },
      { en: 'door', fi: 'doras', img: 'home/door.png' },
      { en: 'floor', fi: 'urlár', img: 'home/floor.png' },
      { en: 'home', fi: 'baile', img: 'home/home.png' },
      { en: 'house', fi: 'teach', img: 'home/house.png' },
      { en: 'kitchen', fi: 'cistin', img: 'home/kitchen.png' },
      { en: 'lamp', fi: 'lampa', img: 'home/lamp.png' },
      { en: 'light', fi: 'solas', img: 'home/light.png' },
      { en: 'living room', fi: 'seomra suí', img: 'home/living_room.png' },
      { en: 'mirror', fi: 'scáthán', img: 'home/mirror.png' },
      { en: 'pillow', fi: 'piliúr', img: 'home/pillow.png' },
      { en: 'room', fi: 'seomra', img: 'home/room.png' },
      { en: 'sofa', fi: 'tolg', img: 'home/sofa.png' },
      { en: 'table', fi: 'bord', img: 'home/table.png' },
      { en: 'wall', fi: 'balla', img: 'home/wall.png' },
      { en: 'window', fi: 'fuinneog', img: 'home/window.png' }
    ]
  },

{
  name: 'Briathra Coitianta — Common Verbs',
  wordsAndImages: [
{ en: 'drink', fi: 'ól', img: 'verbs1/drink.jfif' },
{ en: 'drive', fi: 'tiomáin', img: 'verbs1/drive.jfif' },
{ en: 'eat', fi: 'ith', img: 'verbs1/eat.jfif' },
{ en: 'give', fi: 'tabhair', img: 'verbs1/give.jfif' },
{ en: 'hear', fi: 'clois', img: 'verbs1/hear.jfif' },
{ en: 'laugh', fi: 'gáir', img: 'verbs1/laugh.jfif' },
{ en: 'lift', fi: 'ardóigh', img: 'verbs1/lift.jfif' },
{ en: 'listen', fi: 'éist', img: 'verbs1/listen.jfif' },
{ en: 'look', fi: 'féach', img: 'verbs1/look.jfif' },
{ en: 'open', fi: 'oscail', img: 'verbs1/open.jfif' },
{ en: 'pull', fi: 'tarraing', img: 'verbs1/pull.jfif' },
{ en: 'push', fi: 'brúigh', img: 'verbs1/push.jfif' },
{ en: 'run', fi: 'rith', img: 'verbs1/run.jfif' },
{ en: 'say', fi: 'abair', img: 'verbs1/say.jfif' },
{ en: 'see', fi: 'feic', img: 'verbs1/see.jfif' },
{ en: 'sit', fi: 'suigh', img: 'verbs1/sit.jfif' },
{ en: 'sleep', fi: 'codail', img: 'verbs1/sleep.jfif' },
{ en: 'talk', fi: 'labhair', img: 'verbs1/talk.jfif' },
{ en: 'think', fi: 'smaoinigh', img: 'verbs1/think.jfif' },
{ en: 'walk', fi: 'siúil', img: 'verbs1/walk.jfif' },
{ en: 'want', fi: 'teastaigh', img: 'verbs1/want.jfif' },
{ en: 'wash', fi: 'nigh', img: 'verbs1/wash.jfif' },
{ en: 'write', fi: 'scríobh', img: 'verbs1/write.jfif' },

  ]
},


{
  name: 'Tuilleadh Briathra — More Verbs',
  wordsAndImages: [
    { en: 'blow', fi: 'séid', img: 'verbs2/blow.jfif' },
{ en: 'clean', fi: 'glan', img: 'verbs2/clean.jfif' },
{ en: 'cry', fi: 'caoin', img: 'verbs2/cry.jfif' },
{ en: 'dig', fi: 'tochail', img: 'verbs2/dig.jfif' },
{ en: 'draw', fi: 'tarraing', img: 'verbs2/draw.jfif' },
{ en: 'fall', fi: 'titim', img: 'verbs2/fall.jfif' },
{ en: 'find', fi: 'aimsigh', img: 'verbs2/find.jfif' },
{ en: 'hide', fi: 'folaigh', img: 'verbs2/hide.jfif' },
{ en: 'hug', fi: 'barróg a thabhairt', img: 'verbs2/hug.jfif' },
{ en: 'jump', fi: 'léim', img: 'verbs2/jump.jfif' },
{ en: 'kiss', fi: 'póg', img: 'verbs2/kiss.jfif' },
{ en: 'lie down', fi: 'luigh', img: 'verbs2/lie_down.jfif' },
{ en: 'paint', fi: 'péinteáil', img: 'verbs2/paint.jfif' },
{ en: 'pay', fi: 'íoc', img: 'verbs2/pay.jfif' },
{ en: 'plant', fi: 'cur', img: 'verbs2/plant.jfif' },
{ en: 'ski', fi: 'sciáil', img: 'verbs2/ski.jfif' },
{ en: 'ski downhill', fi: 'sciáil síos', img: 'verbs2/ski_downhill.jfif' },
{ en: 'smell', fi: 'bolmhaigh', img: 'verbs2/smell.jfif' },
{ en: 'swim', fi: 'snámh', img: 'verbs2/swim.jfif' },
{ en: 'taste', fi: 'blaiseadh', img: 'verbs2/taste.jfif' },
{ en: 'throw', fi: 'caith', img: 'verbs2/throw.jfif' },
{ en: 'vacuum', fi: 'folúsghlan', img: 'verbs2/vacuum.jfif' },
{ en: 'wake up', fi: 'dúisigh', img: 'verbs2/wake_up.jfif' },
  ]
}

]